import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { Expense, Member, ExpenseCategory } from '../types';
import { CATEGORY_META } from '../types';

export const exportGroupExpenses = (
    groupName: string,
    expenses: Expense[],
    members: Member[]
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    // ─── Header ───
    // Background for header
    doc.setFillColor(99, 102, 241); // Indigo-500 (#6366f1)
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('SynSplit Statement', 14, 25);

    // Group Name
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    const groupText = `Group: ${groupName}`;
    const groupTextWidth = doc.getTextWidth(groupText);
    doc.text(groupText, pageWidth - 14 - groupTextWidth, 25);

    // Date Generated
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    const dateText = `Generated: ${format(new Date(), 'dd MMM yyyy, HH:mm')}`;
    doc.text(dateText, 14, 35);

    // ─── Summary Section ───
    const totalAmount = expenses.reduce((sum, e) => sum + e.amount, 0);

    doc.setTextColor(50, 50, 50);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Expenses: ${totalAmount.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 14, 50);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Transactions: ${expenses.length}`, 14, 56);

    // ─── Table ───
    const tableColumn = ["Date", "Description", "Category", "Paid By", "Amount"];
    const tableRows: string[][] = [];

    expenses.forEach(expense => {
        const date = format(new Date(expense.createdAt), 'dd MMM yyyy');
        const category = CATEGORY_META[expense.category as ExpenseCategory]?.label || expense.category;

        let payerName = 'Unknown';
        if (expense.paidBy === 'pool') {
            payerName = 'Pool';
        } else {
            const member = members.find(m => m.uid === expense.paidBy);
            payerName = member ? member.name.split(' ')[0] : 'Unknown';
        }

        const amount = `Rs ${expense.amount.toLocaleString('en-IN')}`;

        tableRows.push([date, expense.description, category, payerName, amount]);
    });

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 65,
        theme: 'grid',
        headStyles: {
            fillColor: [99, 102, 241], // Indigo-500
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            halign: 'center'
        },
        styles: {
            font: 'helvetica',
            fontSize: 10,
            cellPadding: 3,
            valign: 'middle',
            overflow: 'linebreak',
            lineColor: [230, 230, 230],
            lineWidth: 0.1,
        },
        columnStyles: {
            0: { cellWidth: 30 }, // Date
            1: { cellWidth: 'auto' }, // Description
            2: { cellWidth: 30 }, // Category
            3: { cellWidth: 30 }, // Paid By
            4: { cellWidth: 30, halign: 'right', fontStyle: 'bold' }, // Amount
        },
        alternateRowStyles: {
            fillColor: [249, 250, 251] // Gray-50
        },
        foot: [[
            'Total', '', '', '',
            totalAmount.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })
        ]],
        footStyles: {
            fillColor: [240, 240, 240],
            textColor: [50, 50, 50],
            fontStyle: 'bold',
            halign: 'right'
        }
    });

    // ─── Footer ───
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);

        const footerText = 'Generated by SynSplit';
        const linkText = 'synsplit.sayanmandal.in';

        const footerY = pageHeight - 10;

        // Centered Footer
        const textWidth = doc.getTextWidth(`${footerText} - ${linkText}`);
        const xConf = (pageWidth - textWidth) / 2;

        doc.text(footerText, xConf, footerY);
        doc.setTextColor(99, 102, 241); // Link color
        doc.textWithLink(linkText, xConf + doc.getTextWidth(footerText) + 2, footerY, { url: 'https://synsplit.sayanmandal.in' });
    }

    // Save PDF
    doc.save(`SynSplit_${groupName.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};
